using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AFMProj.DMS
{
    public class VFCols
    {
        public static String[] TypeID1 = new String[]
            {"INSP_ID","รหัสงาน",
            "INSP_CNT","จำนวนครั้งการตรวจสอบ",
            "OFFICE_NAME","สานักงาน กสทช. เขต",
            "S_NAME","ชื่อสถานี",
            "ST_TYPE_ID","ประเภทสถานีวิทยุคมนาคม",
            "REFERENCE","การตรวจสอบตามแผน",
            "FREQUENCY","ความถี่",
            "COORDINATOR_NAME","ชื่อผู้ประสานงาน",
            "COORDINATOR_TEL","เบอร์โทรศัพ์ผู้ประสานงาน",
            "LICENSE_STATUS","สถานะของใบอนุญาต",
            "LICENSENO","เลขที่ใบอนุญาต",
            "LICENSEISSUE","วันที่ออกใบอนุญาต",
            "LICENSEEXP","วันที่ใบอนุญาตหมดอายุ",
            "ADDRESS","ที่อยู่",
            "LATITUDE","ตำแหน่ง LAT",
            "LONGITUDE","ตำแหน่ง LONG",
            "ABOVE_MINSEA","ความสูงเหนือระดับน้าทะเล",
            "FREQ_MEAS","ความถี่ที่วัดได้",
            "EMISSION","กาลังส่ง(วัตต์)",
            "FREQ_GAIN","อัตราขยายสายอากาศ",
            "INSP_MACHINE","เครื่องมือวัดของสถานีวิทยุ",
            "AERIALLINE_TYPE","UHF TV Panel Antenna",
            "AERIALLINE_HEIGHT","ความสูง",
            "INSP_DESC","รายละเอียดการแพร่คลื่นความถี่ของสถานีวิทยุ",
            "INSP_COMMENT","ความเห็นผู้ตรวจของสถานีวิทยุ",
            "INSP_DATEF","วันที่ตรวจสอบเริ่มต้นของสถานีวิทยุ",
            "INSP_DATET","วันที่ตรวจสอบสิ้นสุดของสถานีวิทยุ",
            "REPORT_DATEF","วันที่รายงานเริ่มต้นของสถานีวิทยุ",
            "REPORT_DATET","วันที่รายงานสิ้นสุดของสถานีวิทยุ",

            "INSP_NAME1","ผู้ตรวจสอบที่ 1",
            "INSP_POSITION1","ตำแหน่งผู้ตรวจสอบที่ 1",
            "INSP_NAME2","ผู้ตรวจสอบที่ 2",
            "INSP_POSITION2","ตำแหน่งผู้ตรวจสอบที่ 2",
            "INSP_NAME3","ผู้ตรวจสอบที่ 3",
            "INSP_POSITION3","ตำแหน่งผู้ตรวจสอบที่ 3",
            "INSP_NAME4","ผู้ตรวจสอบที่ 4",
            "INSP_POSITION4","ตำแหน่งผู้ตรวจสอบที่ 4",
            "DIRECTOR","ผู้อำนวยการ",
            "APPROVE_POSITION","ตำแหน่งอนุมัติ"};


        public static String[] TypeID2 = new String[]
            {"INSP_ID","รหัสงาน",
                "INSP_CNT","จำนวนครั้งการตรวจสอบ",
                "OFFICE_NAME","สานักงาน กสทช. เขต",
                "S_NAME","ชื่อสถานี",
                "ST_TYPE_ID","ประเภทสถานีวิทยุคมนาคม",
                "FREQ_ASSIGN","ความถี่",
                "INSP_REFERENCE","การตรวจสอบตามแผน",
                "COORDINATOR_NAME","ชื่อผู้ประสานงาน",
                "COORDINATOR_TEL","เบอร์โทรศัพ์ผู้ประสานงาน",
                "LICENSE_STATUS","สถานะของใบอนุญาต",
                "LICENSENO","เลขที่ใบอนุญาต",
                "LICENSEISSUE","วันที่ออกใบอนุญาต",
                "LICENSEEXP","วันที่ใบอนุญาตหมดอายุ",
                "ADDRESS","ที่อยู่",
                "LATITUDE","ตำแหน่ง LAT",
                "LONGITUDE","ตำแหน่ง LONG",
                "FREQ_MEAS","ความถี่ที่วัดได้",
                "EMISSION","กาลังส่ง(วัตต์)",
                "FREQ_GAIN","อัตราขยายสายอากาศ",
                "INSP_MACHINE","เครื่องมือวัดของสถานีวิทยุ",
                "AERIALLINE_TYPE","UHF TV Panel Antenna",
                "AERIALLINE_HEIGHT","ความสูง",
                "INSP_DESC","รายละเอียดการแพร่คลื่นความถี่ของสถานีวิทยุ",
                "INSP_COMMENT","ความเห็นผู้ตรวจของสถานีวิทยุ",
                "INSP_DATEF","วันที่ตรวจสอบเริ่มต้นของสถานีวิทยุ",
                "INSP_DATET","วันที่ตรวจสอบสิ้นสุดของสถานีวิทยุ",
                "REPORT_DATEF","วันที่รายงานเริ่มต้นของสถานีวิทยุ",
                "REPORT_DATET","วันที่รายงานสิ้นสุดของสถานีวิทยุ",
                "INSP_NAME1","ผู้ตรวจสอบที่ 1",
                "INSP_POSITION1","ตำแหน่งผู้ตรวจสอบที่ 1",
                "INSP_NAME2","ผู้ตรวจสอบที่ 2",
                "INSP_POSITION2","ตำแหน่งผู้ตรวจสอบที่ 2",
                "INSP_NAME3","ผู้ตรวจสอบที่ 3",
                "INSP_POSITION3","ตำแหน่งผู้ตรวจสอบที่ 3",
                "INSP_NAME4","ผู้ตรวจสอบที่ 4",
                "INSP_POSITION4","ตำแหน่งผู้ตรวจสอบที่ 4",
                "DIRECTOR","ผู้อำนวยการ",
                "APPROVE_POSITION","ตำแหน่งอนุมัติ"};

         public static String[] TypeID3 = new String[]
            {
                "INSP_ID","รหัสงาน",
                "INSP_CNT","จำนวนครั้งการตรวจสอบ",
                "OFFICE_NAME","สานักงาน กสทช. เขต",
                "REFERENCE","อ้างอิง",
                "S_NAME","ชื่อสถานี",
                "ST_TYPE_ID","ประเภทสถานีวิทยุคมนาคม",
                "FREQUENCY","ความถี่ (MHz)",
                "LICENSENO","เลขที่ใบอนุญาต",
                "LICENSEISSUE","วันที่ออกใบอนุญาต",
                "LICENSEEXP","วันที่ใบอนุญาตหมดอายุ",
                "ADDRESS","ที่อยู่",
                "LATITUDE","ตำแหน่ง LAT",
                "LONGITUDE","ตำแหน่ง LONG",
                "FREQ_MEAS","ความถี่ที่วัดได้",
                "AERIALTYPE_ID","ชนิด",
                "AERIALLINE_TYPE","ชนิดสายอากาศ",
                //"EMISSION","กำลังส่ง",
                "FREQ_GAIN","อัตราขยายสายอากาศ",
                "AERIALLINE_HEIGHT","ความสูงสายอากาศ",
                "INSP_DESC","รายละเอียดการแพร่คลื่นความถี่ของสถานีวิทยุ",
                "INSP_COMMENT","ความเห็นผู้ตรวจของสถานีวิทยุ",
                "INSP_MACHINE","เครื่องมือในการทดสอบ",
                "INSP_DATEF","วันที่ตรวจสอบเริ่มต้นของสถานีวิทยุ",
                "INSP_DATET","วันที่ตรวจสอบสิ้นสุดของสถานีวิทยุ",
                "REPORT_DATEF","วันที่รายงานเริ่มต้นของสถานีวิทยุ",
                "REPORT_DATET","วันที่รายงานสิ้นสุดของสถานีวิทยุ",
                "INSP_NAME1","ผู้ตรวจสอบที่ 1",
                "INSP_POSITION1","ตำแหน่งผู้ตรวจสอบที่ 1",
                "INSP_NAME2","ผู้ตรวจสอบที่ 2",
                "INSP_POSITION2","ตำแหน่งผู้ตรวจสอบที่ 2",
                "INSP_NAME3","ผู้ตรวจสอบที่ 3",
                "INSP_POSITION3","ตำแหน่งผู้ตรวจสอบที่ 3",
                "INSP_NAME4","ผู้ตรวจสอบที่ 4",
                "INSP_POSITION4","ตำแหน่งผู้ตรวจสอบที่ 4",
                "DIRECTOR","ผู้อำนวยการ",
                "APPROVE_POSITION","ตำแหน่งอนุมัติ"
            };

         public static String[] TypeID4 = new String[]
            {
                "INSP_CNT","จำนวนครั้งการตรวจสอบ",
                "OFFICE_NAME","สานักงาน กสทช. เขต",
                "S_NAME","ชื่อร้าน",
                "ST_TYPE_ID","ประเภทร้าน",
                //"CLASS_STATION","ประเภท",
                "LICENSENO","เลขที่ใบอนุญาต",
                "LICENSEISSUE","วันที่ออกใบอนุญาต",
                "LICENSEEXP","วันที่ใบอนุญาตหมดอายุ",
                "ADDRESS","ที่อยู่",
                "CURRENT_LAT","ตำแหน่ง LAT",
                "CURRENT_LONG","ตำแหน่ง LONG",
                "RESULT_DESC","ผลการตรวจสอบ",
                "COMMENT_DESC","ความเห็นผู้ตรวจ",
                "INSP_DATEF","วันที่ตรวจสอบเริ่มต้นของสถานีวิทยุ",
                "INSP_DATET","วันที่ตรวจสอบสิ้นสุดของสถานีวิทยุ",
                "REPORT_DATEF","วันที่รายงานเริ่มต้นของสถานีวิทยุ",
                "REPORT_DATET","วันที่รายงานสิ้นสุดของสถานีวิทยุ",
                "INSP_NAME1","ผู้ตรวจสอบที่ 1",
                "INSP_POSITION1","ตำแหน่งผู้ตรวจสอบที่ 1",
                "INSP_NAME2","ผู้ตรวจสอบที่ 2",
                "INSP_POSITION2","ตำแหน่งผู้ตรวจสอบที่ 2",
                "INSP_NAME3","ผู้ตรวจสอบที่ 3",
                "INSP_POSITION3","ตำแหน่งผู้ตรวจสอบที่ 3",
                "INSP_NAME4","ผู้ตรวจสอบที่ 4",
                "INSP_POSITION4","ตำแหน่งผู้ตรวจสอบที่ 4",
                "DIRECTOR","ผู้อำนวยการ"

                };
    }
}